apiVersion: apps/v1
kind: Deployment
metadata:
  name: meuapp
spec:
  selector:
    matchLabels:
      app: meuapp
  template:
    metadata:
      labels:
        app: meuapp
    spec:
      containers:
      - name: meuapp
        image: rukasu/cluster-attack-console:v3
        env:
          - name: APP_NAME
            value: "Cluster Chaos"
        envFrom:
          - configMapRef:
              name: meuconfigmap
          - secretRef:
              name: meusecret
        startupProbe:
          httpGet:
            port: 3000
            path: /health
          periodSeconds: 10
          failureThreshold: 30
        readinessProbe:
          httpGet:
            port: 3000
            path: /ready
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 1
          successThreshold: 1
        livenessProbe:
          httpGet:
            port: 3000
            path: /health
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: meuservice
spec:
  selector:
    app: meuapp
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: meuconfigmap
data:
  APP_REGION: "BR/pt"

